import tailwindcssAnimate from "tailwindcss-animate";

/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        cream: "var(--color-cream)",
        ink: "var(--color-ink)",
        electric: "var(--color-electric)",
        rule: "var(--color-rule)",
        primary: "var(--color-primary)",
        "on-primary": "var(--color-on-primary)",
        secondary: "var(--color-secondary)",
        "secondary-container": "var(--color-secondary-container)",
        "on-secondary": "var(--color-on-secondary)",
        "secondary-text": "var(--color-secondary-text)",
        surface: "var(--color-surface)",
        "surface-bright": "var(--color-surface-bright)",
        "surface-variant": "var(--color-surface-variant)",
        "surface-container": "var(--color-surface-container)",
        "surface-container-low": "var(--color-surface-container-low)",
        "surface-container-high": "var(--color-surface-container-high)",
        "surface-container-highest": "var(--color-surface-container-highest)",
        "on-surface": "var(--color-on-surface)",
        "on-surface-variant": "var(--color-on-surface-variant)",
        outline: "var(--color-outline)",
        "outline-variant": "var(--color-outline-variant)",
        "cta-bg": "var(--color-cta-bg)",
        "cta-text": "var(--color-cta-text)",
      },
      fontFamily: {
        display: ["'Archivo Narrow'", "Archivo", "sans-serif"],
        headline: ["'Archivo Narrow'", "Archivo", "sans-serif"],
        body: ["Inter", "sans-serif"],
        mono: ["'JetBrains Mono'", "monospace"],
        "headline-lg": ["'Archivo Narrow'", "Archivo", "sans-serif"],
        "headline-md": ["'Archivo Narrow'", "Archivo", "sans-serif"],
        "headline-sm": ["'Archivo Narrow'", "Archivo", "sans-serif"],
        "display-xl": ["'Archivo Narrow'", "Archivo", "sans-serif"],
        "display-lg": ["'Archivo Narrow'", "Archivo", "sans-serif"],
        "label-lg": ["'JetBrains Mono'", "monospace"],
        "label-md": ["'JetBrains Mono'", "monospace"],
        "label-sm": ["'JetBrains Mono'", "monospace"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
      },
      fontSize: {
        "display-xl": ["96px", { lineHeight: "0.92", letterSpacing: "-0.04em", fontWeight: "800" }],
        "display-xl-mobile": ["52px", { lineHeight: "0.95", letterSpacing: "-0.03em", fontWeight: "800" }],
        "display-lg": ["64px", { lineHeight: "1.05", letterSpacing: "-0.03em", fontWeight: "800" }],
        "display-lg-mobile": ["38px", { lineHeight: "1.08", letterSpacing: "-0.02em", fontWeight: "800" }],
        "headline-lg": ["44px", { lineHeight: "1.08", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["32px", { lineHeight: "1.12", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-sm": ["24px", { lineHeight: "1.16", letterSpacing: "0em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "400" }],
        "body-md": ["15px", { lineHeight: "24px", letterSpacing: "0em", fontWeight: "400" }],
        "body-sm": ["13px", { lineHeight: "20px", letterSpacing: "0em", fontWeight: "400" }],
        "label-lg": ["14px", { lineHeight: "18px", letterSpacing: "0.02em", fontWeight: "500" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.04em", fontWeight: "500" }],
        "label-sm": ["10px", { lineHeight: "14px", letterSpacing: "0.06em", fontWeight: "500" }],
      },
      spacing: {
        gutter: "1.5rem",
        "gutter-mobile": "1rem",
        margin: "3rem",
        "margin-mobile": "1.25rem",
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-lg": "2rem",
        "space-xl": "4rem",
        "space-2xl": "7rem",
      },
    },
  },
  plugins: [tailwindcssAnimate],
};
